### PR TITLE
Now throwing for some dds initialization errors instead of exiting

### PR DESCRIPTION
**Pull request by doug1234**
Eventually these can be handled in opendds-monitor.

### CODE REVIEW

**Comment by doug1234** [comment]
That doesn't seem to be my doing.  Looks like something is messed up in CI again.

**Review by jrw972 — APPROVED** [review]

**Comment by doug1234** [comment]
Anyone know why windows builds are failing now.  Looks like some packages need an update but nothing else has changed so I don't understand why.

**Comment by mitza-oci** [comment]
Try updating the vcpkg version to match what's used in OpenDDS (if it's not already)

**Comment by doug1234** [comment]
Working now.  The fact that the vcpkg commit needs to be updated every so often or it stops build seems bad to me.

**Comment by mitza-oci** [comment]
> Working now. The fact that the vcpkg commit needs to be updated every so often or it stops build seems bad to me.

run-vcpkg (the GitHub Action) is always pinned to a specific commit.  It's unfortunate that these older ones stop working, but they need to download HTTP resources for dependencies and sometimes those URLs themselves stop working and don't provide redirects.

**Pull request merged**
