### PR TITLE
Build with 3.25

### PR DESCRIPTION
**Pull request by doug1234**

### CODE REVIEW

**Comment by doug1234** [comment]
This doesn't seem to be building because it is using the head of master instead of the 3.25 tag for the CI process.  That is annoying.

**Comment by mitza-oci** [comment]
> This doesn't seem to be building because it is using the head of master instead of the 3.25 tag for the CI process. That is annoying.

It's both, some CI jobs use latest-release and others use master.
Assuming we want to keep that in place, it would need to use preprocessor conditionals to build either way (or OpenDDS would need to change)

**Comment by doug1234** [comment]
It isn't going to build both with 3.25 and master due to recent changes.  Should I change this PR to work with master?  Is there going to be a new official release soon?

It would seem to me to be smoother to just submodule opendds at a particular version which we know works but I guess you don't want to do it that way.

**Comment by jrw972** [comment]
I think we can emulate the raw configuration values.  https://github.com/OpenDDS/OpenDDS/pull/4255

**Comment by jrw972** [comment]
Kicking off new builds.

**Comment by doug1234** [comment]
This PR is building with 3.25 but still not building with master.  Is there a tweak I should make that can get it to build with both or should I make changes to build with master and move on?

**Comment by jrw972** [comment]
Let me take another crack at it.  I didn't account for assignment in that way.  I should be able to replicate it with a unit test.

**Comment by jrw972** [comment]
https://github.com/OpenDDS/OpenDDS/pull/4270

**Comment by jrw972** [comment]
https://github.com/OpenDDS/OpenDDS/pull/4272

**Comment by doug1234** [comment]
Looks like it built and failed again.  Are there more variables I should remove for openddw or is this something that needs to change in opendds?

**Comment by jrw972** [comment]
> Looks like it built and failed again. Are there more variables I should remove for openddw or is this something that needs to change in opendds?

There were more changes from https://github.com/OpenDDS/OpenDDS/pull/4272

**Comment by doug1234** [comment]
Looks like things are passing now.  Can this update be merged?

**Review by simpsont-oci — APPROVED** [review]

**Pull request merged**
