### PR TITLE
Updated link target and using PROJECT_SOURCE_DIR 

### PR DESCRIPTION
**Pull request by doug1234**
A couple of fixed to be more correct and fix our build.  We should only link against what is actually needed and PROJECT_SOURCE_DIR is the correct directory to use so it does not break when the cmake file is nested.

### CODE REVIEW

**Comment by doug1234** [comment]
Not getting these errors when I build locally with the RTPS_Udp.  Is there a build flag that should be passed to make the CI build happy.

**Comment by iguessthislldo** [comment]
It looks like RapidJSON is there when OpenDDS is built, but for some reason it's missing when OpenDDS is restored from the cache. @simpsont-oci, @mitza-oci, any ideas? Are the submodules getting initialized?

**Comment by simpsont-oci** [comment]
Hmm... the rapidjson files were never included in the cache, as they're not part of what's built by OpenDDS. I suppose the CI steps for initializing the submodules should be included regardless of whether the cache hits or misses?

**Comment by mitza-oci** [comment]
Re-test after #11 is merged

**Comment by doug1234** [comment]
Looks like it is still failing...

**Comment by simpsont-oci** [comment]
> Looks like it is still failing...

You'll need to merge master or rebase your branch to pick up the CI changes.

**Comment by doug1234** [comment]
Ah right... looking good now.  Hopefully it can be merged.

**Review by iguessthislldo — APPROVED** [review]

**Pull request merged**
